// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BugTracker.Data
{
    [Table("Bug")]

    public partial class Bug
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int BugID { get; set; }
        [Required]
        [MaxLength(250)]
        public string BugTitle { get; set; }
        public string BugDescription { get; set; }
        public int AssignedUserID { get; set; }
        public short BugStatusID { get; set; }
        public DateTime? DateCreated { get; set; }
        public DateTime? DateModified { get; set; }
    }
}