// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BugTracker.Data
{
    [Table("BugStatus")]
    public partial class BugStatus
    {
        [Key]        
        public short BugStatusID { get; set; }
        public string BugStatusName { get; set; }
    }
}